### ISSUE TITLE
welcome.py issue: 'Exponential' vs 'EllExponential'

### ISSUE THREAD

**Issue by kassidy-kollmann** [Jammy2211/autolens_workspace#14]
Hello!

I am working on getting PyAutoLens set up (following the 'Installation with conda' steps) but I am experiencing an issue with running the welcome.py script. At the stage of the script where it tries to plot an image in PyAutoLens using MatPlotLib, I am getting the following error:
`Traceback (most recent call last):
  File "/Users/kassidy/PyAutoLens/autolens_workspace/welcome.py", line 97, in <module>
    sersic_light_profile = al.lp.Exponential(
AttributeError: module 'autogalaxy.profiles.light_profiles' has no attribute 'Exponential'. Did you mean: 'EllExponential'?`

I changed the backend entry in the config file as the script suggests, but I am still getting the same error. I looked in the autogalaxy.profiles.light_profiles file and I also don't see the Exponential class, but I do see the EllExponential class. 

Is this error due to the backend being set up incorrectly or should I just change the line in welcome.py to al.lp.EllExponential?

Thank you for your help!

**Comment by Jammy2211** [comment]
HI! :)

We did a big release on Sunday night (still pushing a few things through, which is why we haven't put the release on GitHub yet).

It looks like you got caught between the new release, with your autolens an old version but your workspace a new one.

In fact, it looks like our readthedocs didn't update, which is the problem.

Anyway, to fix it you should just need a `pip install autolens==2022.11.26.11`

Thanks for pointing this out!

**Comment by kassidy-kollmann** [comment]
Hello! 

Thank you so much for your response. I meant to respond last week to let you know that this fixed my problem instantly!
