### ISSUE TITLE
Understanding lensed image creation / issue with caustics

### ISSUE THREAD

**Issue by kassidy-kollmann** [Jammy2211/autolens_workspace#15]
Hello!

I have two questions about the howtolens notebooks.

1. Firstly, I'm trying to better understand how PyAutoLens creates the lensed image of a source using the Plane object in tutorial_4_planes. I understand the tutorial through determining the source plane coordinates from the image plane coordinates and deflection angles. Then to create the lensed image we run:
`plane_plotter = aplt.PlanePlotter(plane=source_plane, grid=source_plane_grid_2d)
plane_plotter.figures_2d(image=True)`
So to create the lensed image, the only things used are the source_plane, which contains information about the source galaxy redshift and light profile, and the source_plane_grid_2d, which contains the coordinates in the source plane that get deflected into the FOV of interest in the image plane. Then we use the following image to see where certain regions in the source plane end up deflected to in the image plane (and appear to us as the observer).
![Screen Shot 2022-12-08 at 10 38 50 AM](https://user-images.githubusercontent.com/99421159/206489548-54fdd86e-5e7d-4a79-8226-6488bdb70a9d.png)

Please correct me if I'm wrong, but my understanding is that this image shows us what parts of the source galaxy emission lie within the source galaxy grid and will therefore end up deflected into the image plane of interest:
![Screen Shot 2022-12-08 at 10 40 28 AM](https://user-images.githubusercontent.com/99421159/206490089-19cc0248-b20f-4c57-8ce1-08a32e852ab9.png)

Then what I suspect happens to get the lensed image is that PyAutoLens checks what intensity of light lies at each source plane coordinate and then puts that intensity at the coordinate in the image plane that corresponds to that source plane coordinate? I think what I'm most confused about is how PyAutoLens knows at this stage which source plane coordinate corresponds to which image plane coordinate since we did not give PlanePlotter any information about the original image_plane or image_plane_grid_2d? How did it know how to undo the deflection and find the original image_plane_coordinates without being given information about the mass distribution of the lens galaxy? I know the Tracer object is more convenient to use for ray-tracing than this approach, but I want to ensure I understand what PyAutoLens is doing under the hood first.

2. My second question regards a possible bug with how the code is computing the caustics from the critical curves. When I run the following lines from tutorial_5_ray_tracing:
`include_2d = aplt.Include2D(critical_curves=True, caustics=True)`
`tracer_plotter = aplt.TracerPlotter(tracer=tracer, grid=image_plane_grid_2d,include_2d=include_2d)
tracer_plotter.figures_2d_of_planes(plane_grid=True, plane_index=0)
tracer_plotter.figures_2d_of_planes(plane_grid=True, plane_index=1)`
the result is:
![Screen Shot 2022-12-08 at 11 06 01 AM](https://user-images.githubusercontent.com/99421159/206498316-a347eff1-97d5-46f1-bd85-f2a7abbb486a.png)

I believe there is an issue with how it is ray-tracing the critical curve from the image plane to the source plane because the critical curve and caustic appear to be about the same size when I would expect the caustic to enclose a much smaller area. Additionally, I believe the caustic must be contained within the source plane grid since the critical curve is contained within the image plane grid. If this is correct, can you please advise me on how I can resolve this issue with the caustics?

Thank you for your time!

**Comment by Jammy2211** [comment]
> Then what I suspect happens to get the lensed image is that PyAutoLens checks what intensity of light lies at each source plane coordinate and then puts that intensity at the coordinate in the image plane that corresponds to that source plane coordinate?

Yes, this is exactly what happens.

>  I think what I'm most confused about is how PyAutoLens knows at this stage which source plane coordinate corresponds to which image plane coordinate since we did not give PlanePlotter any information about the original image_plane or image_plane_grid_2d? How did it know how to undo the deflection and find the original image_plane_coordinates without being given information about the mass distribution of the lens galaxy?

Ah, good question!

In tutorial 1, you learn that PyAutoLens uses `Grid2D` objects:

`print(type(source_plane_grid_2d))`

Basically, "behind the scenes", these objects store and track a lot of additional information. The API is designed to hide this from the user, but this can confusion.

The following print statement reveals an internal array which maps every coordinate on the `Grid2D` to its corresponding image-pixel integer pixel coordinates:

`print(source_plane_grid_2d.mask.sub_mask_index_for_sub_mask_1d_index)`

I am working on improving the API docs a lot over the next month, and will take a note to ensure this type of detail is included :).

> I believe there is an issue with how it is ray-tracing the critical curve from the image plane to the source plane because the critical curve and caustic appear to be about the same size when I would expect the caustic to enclose a much smaller area. 

Its not a bug due to the internal PyAutoLens calculations (thank God lol) but a poor choice of mass model and visualization on my part.

The red circle in the top figure (image plane) is the radial critical curve, which is very small because for an isothermal mass distribution it is ill-defined. A much larger (red) radial caustic is seen in the source-plane.

The black curve in the figure is the tangential critical curve, which for a spherical mass profile traces to a singularity in the source plane (there is a black blob of a caustic somewhere in your plot, but its basically indistinguishable).

If we make the mass profile a bit more elliptical:

`sis_mass_profile = al.mp.Isothermal(centre=(0.0, 0.0), einstein_radius=1.6, ell_comps=(0.1, 0.1))`

We get a plot which shows the behaviour you describe:

![image](https://user-images.githubusercontent.com/23455639/206525175-9820d29b-87cf-45b5-8a08-06a6d5fe7588.png)

I've taken a note to improve the visualization and models used in this tutorial!

> Additionally, I believe the caustic must be contained within the source plane grid since the critical curve is contained within the image plane grid. If this is correct,

There are similar tricks going on as above, where internal properties of the `Grid2D` are being used to compute the critical curve in the image plane and then ray-trace it to the source plane to calculate and plot the caustic.

**Comment by kassidy-kollmann** [comment]
Thank you so much for your quick response, this was _super_ helpful! Thank you for explaining about the radial versus tangential critical lines and caustics. I've been working with tangential critical lines/caustics, so I did not have good intuition for the radial ones, but this helps a lot!
